---
settings:
  name: ONTAP tools for VMware vSphere 10.2
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: 適用於 VMware vSphere 10.2 文件的 ONTAP 工具
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - section: upgrade
  - section: recover
  - section: migrate
  - section: automation
  - title: 法律聲明
    url: "/legal-notices.html"
