---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: 在部署適用於 VMware vSphere 的 ONTAP 工具之前、您應該先熟悉部署套件的空間需求、以及一些基本的主機系統需求。 
---
= VMware vSphere 部署的 ONTAP 工具先決條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署適用於 VMware vSphere 的 ONTAP 工具之前、您應該先熟悉部署套件的空間需求、以及一些基本的主機系統需求。

您可以搭配 VMware vCenter Server 虛擬應用裝置（ vCSA ）使用適用於 VMware vSphere 的 ONTAP 工具。您應該在支援的 vSphere 用戶端（包括 ESXi 系統）上部署適用於 VMware vSphere 的 ONTAP 工具。



== 系統需求

* * 每個節點的安裝套件空間需求 *
+
** 10 GB 適用於精簡配置的安裝
** 248 GB 、適用於完整佈建的安裝


* * 每個節點的主機系統規模需求 * 根據部署規模和每個節點的建議記憶體如下表所示：


|===


| * 部署類型 * | * CPU* | * 記憶體（ GB ） * 


| 小（ S ） | 8 | 16 


| 中（ M ） | 12 | 24 


| 大（ L ） | 16 | 32 
|===
請參閱下方 < 部署適用於 VMware vSphere 的 ONTAP 工具組態限制 > 一節以取得更多詳細資料。



== 最低儲存與應用程式需求

|===
| 儲存設備、主機和應用程式 | 最低版本需求 


| ONTAP | ONTAP 9 。 12.1 、 9.13.1 、 9.14.1 和 9.15.1 的最新修補程式版本。 


| ESXi主機 | ESXi 7.0.3 


| vCenter 伺服器 | vCenter 7.0U3 


| VASA供應商 | 3.0 


| ova 應用程式 | 10.2 
|===
互通性對照表工具（ IMT ）包含有關支援版本的 ONTAP 、 vCenter Server 、 ESXi 主機和外掛應用程式的最新資訊。

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["互通性對照表工具"^]



== 部署 VMware vSphere ONTAP 工具的組態限制

您可以使用下表做為指南、為 VMware vSphere 設定 ONTAP 工具。

|===


| *部署* | *類型* | * 虛擬工具數 * | * 主機數 * | * 傳輸協定類型 * 


| 輕鬆部署 | 小（ S ） | 約 12 、 000 | 32 | NFS 、 iSCSI 


| 輕鬆部署 | 中（ M ） | 約 24 萬 | 64 | NFS 、 iSCSI 


| 高可用度 | 小（ S ） | 約 24 萬 | 64 | NFS 、 iSCSI 


| 高可用度 | 中（ M ） | 約 50 萬 | 128 | NFS 、 iSCSI 


| 高可用度 | 大（ L ） | 約 100k | 256 [ 注意 ] 表格中的主機數量顯示來自多個 vCenter 的主機總數。 | NFS 、 iSCSI 
|===
如需每個節點主機系統規模調整需求的詳細資訊link:../deploy/prerequisites.html["部署 VMware vSphere ONTAP 工具的必要條件"]、請參閱。



== 適用於 VMware vSphere 的工具 - 儲存複寫介面卡（ ONTAP ）

下表顯示使用適用於 VMware vSphere 的 ONTAP 工具、每個 VMware Live Site Recovery 執行個體所支援的數量。

|===
| * vCenter 部署規模 * | * 小 * | * 中 * 


| 使用陣列型複寫設定來保護的虛擬機器總數 | 2000 | 5000 


| 陣列型複寫保護群組總數 | 250 | 250 


| 每個恢復計畫的保護群組總數 | 50 | 50 


| 複寫的資料存放區數量 | 255 | 255 


| 虛擬機器數量 | 4000 | 7000 
|===
下表顯示 VMware Live Site Recovery 的數量、以及對應的 VMware vSphere 部署規模 ONTAP 工具。

|===


| * VMware Live Site Recovery 執行個體數 * | * ONTAP 工具部署規模 * 


| 最多 4 個 | 小 


| 4 至 8 | 中 


| 超過 8 個 | 大 
|===
如需詳細資訊、請 https://docs.vmware.com/en/VMware-Live-Recovery/services/vmware-live-site-recovery/GUID-3AD7D565-8A27-450C-8493-7B53F995BB14.html["VMware Live Site Recovery 的營運限制"]參閱。



== 部署前檢查

在繼續部署之前、請先確定已備好下列項目：

* vCenter Server 環境已設定及設定。
* （選用）對於自動化使用者： NetApp 提供的 Postman 集合 JSON 檔案會收集到。
* 部署 OVA 的父 vCenter Server 認證已就緒。
+

NOTE: 父 vCenter Server 密碼不應包含這些特殊字元（ $ 、 ' 、 " ）。

* 您擁有 vCenter Server 執行個體的登入認證、 VMware vSphere 的 ONTAP 工具將會連線至部署後進行註冊。
* 瀏覽器快取已刪除。
* 請確定您有三個可用的 IP 位址可供非 HA 部署使用：一個可用的 IP 位址供負載平衡器使用、一個可用的 IP 位址供 Kubernetes 控制面使用、一個 IP 位址供節點使用。對於 HA 部署、除了這三個 IP 位址、您還需要兩個 IP 位址來處理第二個和第三個節點。在指派 HA 和非 HA 部署之前、應先將主機名稱對應至 DNS 上的可用 IP 位址。HA 部署中的所有五個 IP 位址和非 HA 部署中的三個 IP 位址都應位於選取用於部署的同一個 VLAN 上。


* 請確定已發行憑證的網域名稱已對應至多 vCenter 部署中的虛擬 IP 位址、其中必須有自訂 CA 憑證。會執行 _nslookup_ 檢查網域名稱、以檢查網域是否已解析為預期的 IP 位址。應使用負載平衡器 IP 位址的網域名稱和 IP 位址來建立憑證。
* 在非 HA 進階和 HA 組態中安裝適用於 VMware vSphere 10.2 的 ONTAP 工具之前，請參閱知識庫文章： https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/pre-requisites_for_installing_OTV_10.1_and_10.2_in_NonHA_Advanced_and_HA["非 HA 進階和 HA 組態的先決條件"]

