---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 儲存設備後端是 ESXi 主機用於資料儲存的系統。 
---
= 新增儲存後端
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存設備後端是 ESXi 主機用於資料儲存的系統。您可以使用 ONTAP 工具管理員或 vSphere 用戶端 UI 來新增儲存後端。

*關於此工作*

此工作可協助您建置 ONTAP 叢集。當您使用 ONTAP Tools Manager 新增儲存後端時、儲存後端會新增至全域叢集。將全域叢集與 vCenter Server 執行個體建立關聯、以啟用 SVM 使用者來進行 vVols 資料存放區資源配置。

[role="tabbed-block"]
====
.使用 ONTAP 工具管理器
--

NOTE: 從 ONTAP 工具管理員或 ONTAP 工具 API 新增儲存後端時、即為全域。從 vCenter Server API 新增時、儲存後端是本機的。例如、在多租戶設定中、您可以全域新增儲存後端（叢集）、並在本機新增 SVM 以使用 SVM 使用者認證。

*步驟*

. 從網路瀏覽器啟動 ONTAP 工具管理員： `\https://loadBalanceIP:8443/virtualization/ui/`
. 使用您在部署期間提供的 VMware vSphere 管理員認證 ONTAP 工具登入。
. 從側欄中選擇 * 儲存後端 * 。
. 選取*「Add*」。
. 提供伺服器 IP 位址或 FQDN 、使用者名稱和密碼詳細資料、然後選取 * 新增 * 。
+

NOTE: 支援 IPv4 和 IPv6 管理階層。也支援具有管理生命體的 SVM 使用者型認證。



--
.使用 vSphere 用戶端 UI
--

NOTE: 當您使用 vSphere 用戶端 UI 新增儲存後端時、 vVols 資料存放區不支援直接新增 SVM 使用者。

. 使用登入 vSphere 用戶端 `\https://vcenterip/ui`
. 在捷徑頁面中、按一下外掛程式區段下方的 * NetApp ONTAP tools* 。
. 在 ONTAP 工具的左窗格中、瀏覽至 * 儲存後端 * 、然後選取 * 新增 * 。
. 在 * 新增儲存後端 * 視窗中、提供伺服器 IP 位址、使用者名稱、密碼和連接埠詳細資料、然後按一下 * 新增 * 。
+

NOTE: 您可以新增叢集型認證、以及 IPv4 和 IPv6 管理階層、或提供 SVM 管理 LIF 的 SVM 型認證、以直接新增 SVM 使用者。



清單隨即重新整理、您可以在清單中看到新增的儲存後端。

--
====